package javaproject;


import java.util.ArrayList;
//import java.util.HashSet;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author The Phoenix
 */
public class AddSchool extends javax.swing.JFrame {
    School customer;
    ArrayList collid,City;
    Intermediary inter;
    /**
     * Creates new form BookRoom
     * @param inter
     */
    public AddSchool(Intermediary inter) {
        this.customer=customer;
        initComponents();
        this.inter = inter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schoolsea = new javax.swing.JLabel();
        showschoolbtn = new javax.swing.JButton();
        cancelcompare = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        schoolsdisplay = new javax.swing.JTable();
        backtocmp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        schoolsea.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        schoolsea.setText("Schools Search");
        getContentPane().add(schoolsea);
        schoolsea.setBounds(80, 10, 230, 20);

        showschoolbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        showschoolbtn.setText("Show");
        showschoolbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showschoolbtnActionPerformed(evt);
            }
        });
        getContentPane().add(showschoolbtn);
        showschoolbtn.setBounds(10, 260, 90, 23);

        cancelcompare.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelcompare.setText("CANCEL");
        cancelcompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelcompareActionPerformed(evt);
            }
        });
        getContentPane().add(cancelcompare);
        cancelcompare.setBounds(124, 258, 110, 23);

        schoolsdisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "R.K.V.V.", "Kolkata", "C.B.S.E"},
                { new Integer(2), "S.R. Public School", "Delhi", "C.B.S.E"},
                { new Integer(3), "Jaypee School", "Rewa", "C.B.S.E"},
                { new Integer(4), "Saraswati School", "Guna", "M.P."}
            },
            new String [] {
                "S No.", "School", "City", "Board"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(schoolsdisplay);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 36, 341, 188);

        backtocmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backtocmp.setText("BACK");
        backtocmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtocmpActionPerformed(evt);
            }
        });
        getContentPane().add(backtocmp);
        backtocmp.setBounds(264, 258, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 380, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backtocmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtocmpActionPerformed
        // TODO add your handling code here:
        //CustomerService viewFood = new School (this);
        UserIdentification id = new UserIdentification(inter);
        this.setVisible(false);
        id.setVisible(true);
        
    }//GEN-LAST:event_backtocmpActionPerformed

    private void showschoolbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showschoolbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model3= (DefaultTableModel) schoolsdisplay.getModel();
        int schoolsAdded=schoolsdisplay.getSelectedRow();
        
        
        
        System.out.println("Schools Added "+model3.getValueAt(schoolsAdded, 0).toString());
        inter.collid.add(model3.getValueAt(schoolsAdded, 0).toString());
        inter.city.add(model3.getValueAt(schoolsAdded, 1).toString());
        
    }//GEN-LAST:event_showschoolbtnActionPerformed

    private void cancelcompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelcompareActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model5= (DefaultTableModel) schoolsdisplay.getModel();
        int roomBooked=schoolsdisplay.getSelectedRow();
        String collId=model5.getValueAt(roomBooked, 0).toString();
        
        
        for(int i=0;i<inter.collid.size();i++){
            if (inter.collid.get(i).equals(collId))
                inter.collid.remove(collId);
        }
        System.out.println("School id "+ collId+" successfully removed");
        
        
        
    }//GEN-LAST:event_cancelcompareActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtocmp;
    private javax.swing.JButton cancelcompare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable schoolsdisplay;
    private javax.swing.JLabel schoolsea;
    private javax.swing.JButton showschoolbtn;
    // End of variables declaration//GEN-END:variables
}
