package javaproject;


import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author The Phoenix
 */
public class Knt extends javax.swing.JFrame {

    School customer;
    TableUsingArrayList tableUsingArrayList;
    ArrayList names,price;
    Intermediary inter;
    /**
     * Creates new form OrderFood
     *
     * @param inter
     */
    public Knt(Intermediary inter) {
        this.customer = customer;
        initComponents();
        tableUsingArrayList = new TableUsingArrayList(this);
        this.inter = inter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectFoodBtn = new javax.swing.JButton();
        cancelOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTableDisplay = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel1.setText("Know The Best");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 190, 30);

        selectFoodBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectFoodBtn.setText("Show");
        selectFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFoodBtnActionPerformed(evt);
            }
        });
        getContentPane().add(selectFoodBtn);
        selectFoodBtn.setBounds(10, 292, 110, 40);

        cancelOrder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelOrder.setText("CANCEL");
        cancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOrderActionPerformed(evt);
            }
        });
        getContentPane().add(cancelOrder);
        cancelOrder.setBounds(135, 292, 120, 40);

        foodTableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S. No.", "School Name", "City", "Board"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(foodTableDisplay);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 50, 320, 197);

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(270, 290, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void selectFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFoodBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model2 = (DefaultTableModel) foodTableDisplay.getModel();
        int foodOrdered = foodTableDisplay.getSelectedRow();
        
        System.out.println("Compared Schools: "+model2.getValueAt(foodOrdered, 1).toString());
        inter.names.add(model2.getValueAt(foodOrdered, 1).toString());
        inter.collid.add(model2.getValueAt(foodOrdered, 2).toString());
        
       
      

    }//GEN-LAST:event_selectFoodBtnActionPerformed

    

    private void cancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOrderActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model4 = (DefaultTableModel) foodTableDisplay.getModel();
        int foodCanceled = foodTableDisplay.getSelectedRow();
        String foodName=model4.getValueAt(foodCanceled, 1).toString();
        String foodPrice=model4.getValueAt(foodCanceled, 2).toString();
        
        
        for(int i=0;i<inter.names.size();i++){
            if (inter.names.get(i).equals(foodName))
                inter.names.remove(foodName);
        }
        System.out.println( foodName+" successfully removed");
        //System.out.println(inter.names);
        
    }//GEN-LAST:event_cancelOrderActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        UserIdentification id = new UserIdentification(inter);
        this.setVisible(false);
        id.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelOrder;
    public javax.swing.JTable foodTableDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton selectFoodBtn;
    // End of variables declaration//GEN-END:variables

    
}
